tier4/caret_doc

docs/tutorials/setup.md

fix: add pandas version

---

docs/tutorials/setup.md

I'd like to add quick installation guide after merging https://github.com/tier4/caret/pull/7 is approved.

feature: add setup manual with ansible

---

docs/tutorials/measurement.md

Info tag is useful to add supplements.

chore(tutorials): replace quotation by info tag.

---

docs/imgs/measurement_flow.svg
docs/imgs/path_and_node_latency.svg

Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

chore: translate figure description

---

.github/workflows/deploy-docs.yaml

chore(deploy-docs): revert deploy-docs actions

---

docs/index.md

Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

chore: typo

---

docs/tutorials/measurement.md

Signed-off-by: hsgwa <hasegawa.isp@gmail.com>

docs: add build_testing=off to compile option

---

docs/tips/summary_of_trace_data.md

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>
[こちらのチケット](https://docs.google.com/document/d/10vgDrzCmu5PQyFDjyBf9b8KazBJyRVr8-ydWC6fvSaQ/edit) で追加させて頂いたサマリのフィルタリングオプションに関して、CARET_doc を更新しました。
ご確認をお願いいたします。

docs: add docs of filtering option for summary

---

docs/.pages
docs/changelog.md

docs(changelog) add changelog.md

---

docs/tips/.pages
docs/tips/create_and_verify_architecture.md

@hsgwa CC: @keita1523 
[ros2 caret の CLI でアーキテクチャファイルの作成・チェックを可能にする](https://tier4.atlassian.net/browse/T4PB-17111) に関するドキュメントを、CARET_doc の Tips に追加しましたので、ご確認をお願いいたします。

docs: create and verify architecture file with CLI

---

.github/sync-files.yaml

ci: add .spell.json to be synchronized

---

docs/changelog.md
docs/design/.pages
docs/index.md
docs/tips/manual_installation.md
docs/tutorials/installation.md
docs/tutorials/measurement.md

To change target ROS distribution to Humble, I updated the documentation.

docs: updated for Humble version release

---

docs/changelog.md

chore: updated changelog to release v0.3.0.

---

.cspell.json
docs/index.md

ci(cspell-check): change referred cspell dictionary.

---

docs/changelog.md

docs: updated changelog for v0.3.1 tag

---

docs/changelog.md

docs(changelog): updated changelog for tag v0.3.2

---

docs/installation/manual_installation.md

docs: translated manual installation in English

---

docs/changelog.md

docs(changelog): updated changelog for tag v0.3.3

---

docs/design/trace_points/initialization_trace_points.md

In the future, trace points for services should be added to the document.
This document is a draft of that document.

docs(trace points):  add service trace points

---

docs/design/trace_points/runtime_trace_points.md

chore: rename original to built-in tracepoint

---

docs/changelog.md

This PR is necessary for adding new tag, v0.3.4, to CARET.
I added some updates accordingly.

docs(changelog): updated changelog for tag v0.3.4

---

docs/changelog.md

This PR is issued to release v0.4.0. In this PR, I would like to update changelog.md

docs(changelog): updated changelog for tag v0.4.0

---

docs/faq/index.md

Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>
Add FAQ for runtime recording
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-24281)
None

docs: add FAQ for runtime recording

---

docs/faq/index.md

I suppose that `term` is typo of `time`. I fixed it in the PR.

fix(faq): fixed typo

---

docs/changelog.md

This PR is issued to release v0.4.1. In this PR, I would like to update changelog.md
@hsgwa  Could you add your contribution after v0.4.0?

docs(changelog): updated changelog for tag v0.4.1

---

.github/sync-files.yaml

ci: add missing s

---

docs/configuration/inter_node_data_path.md

Signed-off-by: keita1523 <keita.miura@tier4.jp>
Add documents of `Architecture.combine_path()` function.
https://tier4.atlassian.net/browse/T4PB-17677
[T4PB-17677]: https://tier4.atlassian.net/browse/T4PB-17677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: explain combine_path

---

docs/recording/index.md
docs/recording/trace_filtering.md

I'd like to add brief introduction at the beginning of recording chapter.

docs(recording): added introduction of recording chapter

---

docs/design/runtime_processing/runtime_recording.md

docs(design): minor fixes such as typo

---

docs/design/trace_points/initialization_trace_points.md

This PR fixes title rank.
Before:
After:

chore(design): fix title rank in trace points definitions

---

docs/design/runtime_processing/tracepoint_filtering.md
docs/recording/trace_filtering.md

- Fix description added by https://github.com/tier4/CARET_doc/pull/158
- Remove notification about limitation of filtering in DDS layer

fix: fix documents relating to tracepoint filtering in DDS layer

---

docs/configuration/inter_node_data_path.md

Add the document of Path analysis option, `include_first_callback` and `include_last_callback`.
- https://github.com/tier4/CARET_analyze/pull/263

docs(configuration): add explanation of new path definition which includes first/last callback execution

---

docs/recording/sim_time.md

Replace old APIs with new APIs
None
None

docs(recording/sim_time): replace APIs

---

docs/recording/sim_time.md
docs/visualization/index.md

this PR fixes documents for refactoring of Plot package.
- JIRA ticket: https://tier4.atlassian.net/browse/RT2-627

docs(plot): fix documents for refactoring of Plot package.

---

docs/changelog.md

This PR is created for tag v0.4.7. There was a response to the team structure change in this sprint, so the only change is refactoring of the design of Plot package.

docs(changelog): update changelog for tag v0.4.7

---

docs/visualization/frequency/index.md

This PR corrects the documentation for changing the frequency calculations in Communication.
- JIRA ticket: https://tier4.atlassian.net/browse/RT2-238
- Related PR: https://github.com/tier4/CARET_analyze/pull/291#pullrequestreview-1424008872

docs: fix docs for communication frequency

---

docs/changelog.md

This PR is created for tag v0.4.8 tagging on Mar 1st.

docs(changelog): update changelog for tag v0.4.8

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.9

---

docs/faq/known_issues.md

- Add workaround for https://github.com/tier4/caret/issues/89
- https://tier4.atlassian.net/browse/RT2-715
- https://github.com/tier4/caret/pull/90
None

docs(faq): add known_issue for SYSTEM rclcpp referred

---

docs/changelog.md
docs/configuration/load_and_save.md
docs/design/runtime_processing/runtime_recording.md
docs/recording/recording.md
docs/visualization/index.md

Add description about multi-host system to documents.
https://tier4.atlassian.net/browse/RT2-269
None

docs: add description about multi-host system

---

docs/configuration/load_and_save.md
docs/design/runtime_processing/runtime_recording.md
docs/recording/recording.md
docs/visualization/index.md

Reverts tier4/CARET_doc#187. This was simply operation error.

revert: "docs: add description about multi-host system"

---

docs/changelog.md

I created this PR to update changelog for v0.4.10.
https://github.com/tier4/caret/releases/tag/v0.4.10

docs: update changelog for v0.4.10

---

docs/changelog.md

I created this PR to update changelog for v0.4.11.
https://github.com/tier4/caret/releases/tag/v0.4.11

docs(changelog): update changelog for tag v0.4.11

---

docs/changelog.md

I created this PR to update changelog for v0.4.12.

docs(changelog): update changelog for tag v0.4.12

---

docs/design/limits_and_constraints/index.md

This PR will add the following conditions as measurable targets by CARET.
1. The rclcpp library must be used.
2. The processes that act as ROS node.

docs(limits): add measurable application requirements

---

docs/changelog.md

Sorry for the late update, but this PR is the made for the changelog update for CARET v0.4.13.

docs(changelog): update changelog for tag v0.4.13

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.4.14.

docs(changelog): update changelog for tag v0.4.14

---

docs/faq/known_issues.md

The warning by `setup.py` is described in the section on how to deal with it.
Jira: https://tier4.atlassian.net/browse/RT2-793

docs: know issue for warning by setup.py

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.4.15.
- also updated v0.4.14 changelog by adding compatible table for CARET_analyze and trace data.

docs(changelog): update changelog for tag v0.4.15

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.4.17.

docs(changelog): update changelog for tag v0.4.17

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.4.18.

docs(changelog): update changelog for tag v0.4.18

---

docs/design/software_architecture/caret_trace.md
docs/recording/sim_time.md

This PR changes the text to add the c[lock_recorder option](https://github.com/tier4/ros2caret/pull/125).

docs: fix clock_recorder

---

docs/recording/cli_tool.md

update ros2 caret command usage.
Jira: https://tier4.atlassian.net/browse/RT2-975

docs: update ros2 caret command usage

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.4.19.

docs(changelog): update changelog for tag v0.4.19

---

docs/faq/faq.md
docs/recording/build_check.md
docs/recording/validating.md
docs/tutorials/recording.md

The documentation tutorials have been updated due to changes in the ros2 caret command. This PR is likely a result of the following PR.
https://github.com/tier4/caret_doc/commit/d0fd7c94db216efd914f59c48888f8925f24e894
https://tier4.atlassian.net/browse/RT2-975

docs: update ros2 caret command usage 

---

docs/tutorials/visualization.md

fix sample code of message flow

chore: fix sample code of message flow

---

docs/design/trace_points/initialization_trace_points.md

update tracepoint event 'caret_init'
- https://github.com/tier4/caret_trace/pull/150

docs: update caret_init

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.20

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.21

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.22

---

docs/design/limits_and_constraints/index.md
docs/design/trace_points/initialization_trace_points.md
docs/design/trace_points/runtime_trace_points.md
docs/faq/faq.md
docs/installation/installation.md
docs/tutorials/recording.md

docs: added iron tutorial

---

docs/tutorials/recording.md

Fix build procedure.
When building with iron, CARET does not need to use caret-rclcpp.

fix: fix build procedure in iron

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.23

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.24

---

docs/changelog.md

docs(changelog): update changelog for tag v0.4.25

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.2

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.3

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.4

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.5

---

README.md

Fix the path to the `mkdocs-requirements.txt` in README.md.

fix: fix the path to the `mkdocs-requirements.txt`

---

docs/faq/faq.md

precautions when starting at the same time as autoware
https://tier4.atlassian.net/browse/RT2-592

docs: precautions when starting at the same time as autoware

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.6

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.5.8.

docs(changelog): update changelog for tag v0.5.8

---

docs/changelog.md

This PR is the made for the changelog update for CARET v0.5.10.

docs(changelog): update changelog for tag v0.5.10

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.11

---

docs/changelog.md

docs(changelog): update changelog for tag v0.5.12

---

docs/changelog.md

docs(changelog): update changelog for v0.5.13

---

docs/changelog.md

docs(changelog): update changelog for v0.5.14

---

docs/design/limits_and_constraints/index.md
docs/design/trace_points/initialization_trace_points.md
docs/faq/faq.md
docs/installation/installation.md
docs/tutorials/recording.md
mkdocs.yaml

jazzy support
https://tier4.atlassian.net/browse/RT2-1803

feat: jazzy support

---

docs/changelog.md

docs(changelog): update changelog for v0.6.0

---

docs/tutorials/configuration.md
docs/tutorials/visualization.md

Prepare architecture.yaml for jazzy in tutorial visualization
https://tier4.atlassian.net/browse/RT2-1803

fix: prepare architecture.yaml for jazzy
