tier4/caret_doc

docs/index.md
I noticed that I left unaligned words in the overview page. I fixed it.
=> fix: align words used in figure and overview text

docs/tips/gallery.md
I found a simple mistake in gallery page's source code.
=> fix: replace latency_ns with latency_ms

docs/tutorials/measurement.md
Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>
@hsgwa 
[CARET/rclcpp が適用されてビルドしているか確認するためのツール](https://tier4.atlassian.net/browse/T4PB-16473) に関するドキュメントを追加したので、ご確認をお願いいたします。
CARET_v0.2 では、`rclcpp_publisher_init` のトレースポイントを使用したチェックができないため、こちらのコマンドを使用する想定です。
=> docs: add documents of check caret-rclcpp

docs/index.md
I have added a link for accessing API list located in `CARET_analyze`.
=> docs(index): add link for API list in CARET_analyze

docs/tutorials/installation.md
In tutorial chapter, `--recursive` option is no longer necessary for executing `vcs import`. 
This PR is related  with  https://github.com/tier4/CARET_analyze_cpp_impl/pull/17/files .
=> docs(tutorials): remove --recursive

docs/tutorials/visualization.md
sample architecture file defines a path with "target".
https://raw.githubusercontent.com/tier4/CARET_demos/main/samples/end_to_end_sample/architecture.yaml
=> fix(tutorial): modify path name corresponding to the sample architecture file.

docs/recording/recording.md
Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>
Add `ros2_caret:caret_init` to caret_light event filter. Without it, some visualization (like path analysis) doesn't work.
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/T4PB-24857)
=> fix: caret_light event filter

docs/design/configuration/architecture_file.md
This PR adds description for construction_order in architecture file.
Implemented in :
https://github.com/tier4/CARET_analyze/pull/225
=> docs(design): add description for construction_order

docs/design/runtime_processing/tracepoint_filtering.md
Signed-off-by: Nobuhiko Uetsuki <uetsuki@isp.co.jp>
Add description about tracepoint filtering in DDS layer.
=> docs(design): add description about tracepoint filtering in DDS layer

docs/changelog.md, docs/configuration/.pages, docs/configuration/architecture_diff_func.md, docs/configuration/index.md
`Require differences of two architectures` is added to chapter Configuration of CARET_doc.
`Require differences of two architectures` section explains how to use `diff_XXX_YYY` function.
=> docs(configuration): add the explanation of Architecture.diff_* functions

docs/design/trace_points/runtime_trace_points.md
After CARET v4.10, records are merged using the tracepoint `rmw_take`, added in humble. With this change, the `dispatch_subscription_callback trace` point is no longer a critical event in record merge.
- https://github.com/tier4/CARET_trace/pull/113
- https://github.com/tier4/CARET_analyze/pull/296
=> docs: added docs for runtime tracepoints  er-diagram and its definition

docs/recording/recording.md
- `ros2:dispatch_subscription_callback` trace point is replaced with `ros2:rmw_take` by https://github.com/tier4/CARET_trace/pull/113.
- This PR adds `ros2:rmw_take` to light option filter
https://tier4.atlassian.net/browse/RT2-725
https://github.com/tier4/CARET_trace/pull/113
https://github.com/tier4/ros2caret/pull/70
https://github.com/tier4/caret_autoware_launch/pull/5
None
=> fix(recording): add tracepoint for light record

docs/recording/trace_filtering.md
Runtime recording function creates a new node named `caret_trace_*` for each process. It sometimes causes duplicated id warning, and there is no need to trace `caret_trace_*`
https://tier4.atlassian.net/browse/RT2-599
https://github.com/tier4/CARET_trace/pull/68
https://star4.slack.com/archives/C017YM4AA06/p1673595959892529
None
=> fix(recording): update trace filter

deploy-docs/mkdocs-requirements.txt, docs/design/trace_points/runtime_trace_points.md, docs/recording/validating.md
The current CARET does not use message_timestamp, included in `rclcpp_publsh` and `rclcpp_intra_publish`. 
There are plan to eliminate the tracepoint added by forked repositories([rclcpp](https://github.com/tier4/rclcpp/tree/v0.3.0), [ros2_tracing](https://github.com/tier4/ros2_tracing/tree/v0.3.0)) in the future.
Due to the above, it is necessary to unify the signatures and remove message_timestamp from `rclcpp_publsh` and `rclcpp_intra_publish`. 
=> docs: remove message_timestamp from rclcpp_publish and rclcpp_intra_publish

docs/changelog.md
This PR is the made for the changelog update for CARET v0.4.16.1.
I intentionally skipped tag v0.4.16 because there was a bug where cyclonedds were not imported correctly when building CARET.
=> docs(changelog): update changelog for tag v0.4.16.1

docs/faq/faq.md
Added a method to record applications that use [RelayNode](https://github.com/ros-tooling/topic_tools).
RelayNode use GenericPublisher, GenericSubscription which doesn't have necessary trace point for evaluation with CARET.
To record the application containing the RelayNode, it is necessary to rebuild the RelayNode using caret-rclcpp.
- https://github.com/tier4/rclcpp/pull/7
- https://github.com/tier4/caret_trace/pull/220
- https://github.com/tier4/caret_trace/pull/228
=> docs(faq): how to record applications that include RelayNode

docs/design/limits_and_constraints/index.md, docs/faq/faq.md, docs/installation/installation.md
Removed ROS2 Galactic and Ubuntu 20.04 support from the documentation.
Jira: https://tier4.atlassian.net/browse/RT2-1070
=> docs: remove old environments

docs/gallery.md
remove graph of old function (Response Time Histogram) in Gallery.
Jira: https://tier4.atlassian.net/browse/RT2-1307
=> fix: apply remove old API of response time histogram

docs/changelog.md
=> docs(changelog): update changelog for tag v0.5.1

docs/changelog.md
=> docs(changelog): update changelog for tag v0.5.7

docs/changelog.md
This PR is the made for the changelog update for CARET v0.5.9.
=> docs(changelog): update changelog for tag v0.5.9

docs/faq/faq.md
With the numpy2 release, some packages may not work in some environments.
This PR adds a workaround in using CARET.
=> docs: add note for import error related to numpy2 release

docs/changelog.md
=> docs(changelog): update changelog for tag v0.6.1

docs/changelog.md
=> docs(changelog): update changelog for tag v0.6.2

docs/faq/faq.md
Note that RelayNode analysis is not possible with iron.
[https://tier4.atlassian.net/browse/RT2-2362](https://tier4.atlassian.net/browse/RT2-2362)
=> fix: add restrictions on iron

docs/configuration/inter_node_data_path.md
Add link to path search example for large ROS 2 application.
- https://github.com/tier4/caret/issues/215
=> docs: add link to path search example

docs/faq/known_issues.md
- When building the target application using `--merge-install`, a build error may occur
- This PR adds workarounds for this case
[TIER IV INTERNAL LINK](https://tier4.atlassian.net/browse/RT0-39289)
- Adding `Drclcpp` and `Dtracetools` to cspell ignore dictionary was refused, so I use inline ignores
- https://github.com/tier4/autoware-spell-check-dict/pull/860#issuecomment-3273423624
=> docs(known_issue): add extra workarounds for library confliction
